### ISSUE TITLE
Per-channel unread tracking

### ISSUE THREAD

**Issue by cleverdevil** [aaronpk/Aperture#28]
Presently, read/unread tracking it always on. It'd be nice to be able to configure a particular channel to disable read/unread tracking, and to just deliver everything as "read" by default.

**Comment by aaronpk** [comment]
This has been bugging me as well. I have Instagram as a channel, and there are almost always new photos there, so the unread count is pretty much meaningless.

I was also thinking of a third option which is to only track whether or not there are new posts, not the number of new posts. This could show up in the API as `unread: true` rather than `unread: 24`.
